export { default as Navbar } from './Navbar';
export { default as Home } from './Home';
export { default as Routines } from './Routines';
export { default as MyRoutines } from './MyRoutines';
export { default as Activities } from './Activities';
export { default as LogIn } from './LogIn';
export { default as Register } from './Register';
export { default as LogOut } from './LogOut';
export { default as Activity } from './Activity';